### ISSUE TITLE
Could not find artifact ca.bkaw:paper-nms:jar:1.19.2-SNAPSHOT

### ISSUE THREAD

**Issue by TheSerumDev** [Alvinn8/paper-nms-maven-plugin#13]
Here is my pom: https://pastebin.com/KYGufBdA

If I want reload my pom.xml comes this error "Could not find artifact ca.bkaw:paper-nms:jar:1.19.2-SNAPSHOT"

**Comment by Alvinn8** [comment]
Hello. You will need to run `paper-nms:init`. Follow the instructions in the [readme](https://github.com/Alvinn8/paper-nms-maven-plugin#usage-intellij), steps 4 and onwards.

**Comment by TheSerumDev** [comment]
Oh damn... I'm sorry, it works.

Thanks
