### ISSUE TITLE
Maven Plugin is being executed but no remap is being done

### ISSUE THREAD

**Issue by Splitrox** [Alvinn8/paper-nms-maven-plugin#14]
I have a project with some modules lets imagine:
- Foo (module)
- Bar (module)
- Plugin (module)
- Parent (pom)

Plugin module will shade Foo and Bar.

All the modules have the dependency ca.bkaw:paper-nms

Plugin pom.xml have paper-nms-maven-plugin, maven-compiler-plugin and maven-shade-plugin
Parent only have maven-compiler-plugin

When i build the project no error appears, i got a message saying "Remapping classes" but when I take a look at the file no changes have been made.

In this case paper-nms-maven-plugin is only on Plugin module that will have the rest.
Also if i try to put paper-nms-maven-plugin on Foo and Bar error like incompatible or invalid cast and symbol could not be resolved

Any ideas?

**Comment by Alvinn8** [comment]
The paper-nms-maven-plugin will need to be on the Foo and Bar modules. The error you are describing seems like your java code is failing to compile.

**Comment by Splitrox** [comment]
But when i put the plugin on all modules im getting this:

cannot access net.minecraft.world.entity.decoration.EntityArmorStand
[[1;31mERROR[m]   class file for net.minecraft.world.entity.decoration.EntityArmorStand not found
[[1;31mERROR[m] ... cannot find symbol
[[1;31mERROR[m]   symbol:   method getDatabaseType()

It seems I'm having issues with the ArmorStand remapping and the getDatabaseType() it seems is getting problems with lombok 1.18.26. Do you know what i can do?

**Comment by Alvinn8** [comment]
`EntityArmorStand` is a spigot-mapped name. You need to use the Mojang-mapped names (`ArmorStand` in that case). It's the same class, just a different name. You can use [this website](https://nms.screamingsandals.org/1.19.3/) to translate between the names.

**Comment by Splitrox** [comment]
![image](https://user-images.githubusercontent.com/49073687/217506802-25a563ab-e8ab-452d-bcfc-def0cc291102.png)

Also sometimes im getting this on the problem

![image](https://user-images.githubusercontent.com/49073687/217506949-3bceaddf-4591-4c69-8d44-ef3380dfdcac.png)

But it seems that is being used "ArmorStand". I think the problem is more the remapped or not between modules (even if they are using the same dependency and plugin)

**Comment by Alvinn8** [comment]
I am not able to reproduce your issue. Make sure you have compiled everything, it's still referencing `EntityArmorStand` from somewhere. Try a `mvn install` on the parent module.

**Comment by Splitrox** [comment]
mvn install make the error as well

**Comment by Alvinn8** [comment]
I am not able to reproduce the issue. Could you make and share a minimal reproducible example?

**Comment by Alvinn8** [comment]
I think this is the same issue as #16, so the same fix should work here too. If this is a separate issue feel free to reopen the issue!
