### ISSUE TITLE
Can you please bump versions

### ISSUE THREAD

**Issue by SMJSGaming** [Alvinn8/paper-nms-maven-plugin#26]
I'll just give it straight. It has so many vulnerabilities currently that I tried spending 30 minutes overwriting packages just to fix them all, and there was no end in sight. Never in my life have I seen such an unholy amount of vulnerabilities accumulated in one pom, to the point that I basically have to question if running this even locally is safe considering the gigantic list of vulnerability warnings I get from my IDE.

**Comment by Alvinn8** [comment]
If you are referring to the `paper-nms` dependency, I have zero control over that. See #21. I take the Minecraft jar straight from paper and expose that as-is. Dependencies in that is nothing I can change.

If there are vulnerabilities in the __maven plugin__, please let me know which ones so I can update them. I updated most dependencies in version 1.4.3 so it should be quite up to date.
