### ISSUE TITLE
Cannot Access some classes

### ISSUE THREAD

**Issue by Ekpoa** [Alvinn8/paper-nms-maven-plugin#28]
I am using 1.20.6 version, I removed the execution part from the plugin, added the other plugin as stated in the README. 

Getting a few errors for accessing Bukkit classes such;

cannot access org.bukkit.craftbukkit.entity.CraftPlayer

**Comment by Alvinn8** [comment]
Hello! Make sure your project is running Java 21. You can change that in your pom.xml, and in IntelliJ under project structure.
