### ISSUE TITLE
Paper API is shaded when using this plugin

### ISSUE THREAD

**Issue by DerEchtePilz** [Alvinn8/paper-nms-maven-plugin#29]
Okay, maybe I am doing something extremely wrong but I have followed every step in the README.md and have successfully added Paper's internals to the project I am working on.
However, ever since I am using this plugin it seems that the entire Paper API and its dependencies are also shaded which I obviously don't want.
Is this something your plugin might cause? Please scream at me if you need any more information, this is my `pom.xml`, however: https://pastes.dev/EUUR81wshP
This is within the `dev/commandapi-paper` branch on the https://github.com/JorelAli/CommandAPI repository if you need a further look.

**Comment by Alvinn8** [comment]
Hello! This plugin should not change the behavior of the Maven shade plugin.

I took a look at the repository you provided, and it looks like you have `commandapi-paper-core` as a dependency with scope `compile`. Furthermore, `commandapi-paper-core` depends on `paper-api` with scope `compile` ([link](https://github.com/JorelAli/CommandAPI/blob/86a85d5cd6da8a51cb41f2e699e7ae563f4783ae/commandapi-platforms/commandapi-paper/commandapi-paper-core/pom.xml#L52)). The Maven shade plugin will include all dependencies with scope `compile` or `runtime`, and the `compile` scope is transitive. This is likely why `paper-api` is being shaded in your case.

Btw, the `paper-nms` dependency already has `paper-api` as a dependency, so you don't need to add both `paper-nms` and `paper-api` in your pom, just `paper-nms` is sufficient.

**Comment by DerEchtePilz** [comment]
> Furthermore, `commandapi-paper-core` depends on `paper-api` with scope compile ([link](https://github.com/JorelAli/CommandAPI/blob/86a85d5cd6da8a51cb41f2e699e7ae563f4783ae/commandapi-platforms/commandapi-paper/commandapi-paper-core/pom.xml#L52))

Thanks, this was what I was searching for, just a bit embarrassed that I assumed it was your plugin and didn't take a look at other pom files.

> Btw, the `paper-nms` dependency already has `paper-api` as a dependency, so you don't need to add both `paper-nms` and `paper-api` in your pom, just paper-nms is sufficient.

Thanks, I'll keep that in mind.
