### ISSUE TITLE
Add 1.21 Support

### ISSUE THREAD

**Issue by Profiidev** [Alvinn8/paper-nms-maven-plugin#31]
Nice Plugin.
Would it be possible to add 1.21 support?

**Comment by Alvinn8** [comment]
Have you tried it? Most of the time it works out of the box.

**Comment by Profiidev** [comment]
I think the problem is that Minecraft now uses Java 21 instead of 17

**Comment by Alvinn8** [comment]
You need to make sure that maven is running Java 21. If you're running through IntelliJ make sure your project is using Java 21. If it's still not working, do you get an error message that you could show?

**Comment by Profiidev** [comment]
I used Java 21. I am currently not at home I can give you the full error later  but it says something like Unsupported class version

**Comment by Profiidev** [comment]
This stage fails
```
[INFO] 
[INFO] --- paper-nms:1.3.2:remap (default) @ PluginName ---
[INFO] Remapping classes
```
with this error
```
Unsupported class file major version 65
```

**Comment by Profiidev** [comment]
I also don't think that these kinds of imports will work in 1.21
```
import org.bukkit.craftbukkit.v1_20_R2.CraftWorld;
```

**Comment by Alvinn8** [comment]
You are using version 1.3.2 of paper-nms-maven-plugin, which is an almost 2-years-old version. Please update to 1.4.4 and it should work.

**Comment by Profiidev** [comment]
Thanks. Package works now but my plugin does not work on spigot so I maybe have to wait for paper release
